const fs = require('fs')
const path = require('path')
const imageSize = require('image-size')
const {execSync} = require('child_process')

const SRC_DIR = path.join(__dirname, './src')
const OUTPUT_FILE = path.join(SRC_DIR, 'src/assets/AppLocalImage.tsx')

const IMAGE_EXTENSIONS = ['.png', '.jpg', '.jpeg']

function findImages(dir, images = []) {
  const files = fs.readdirSync(dir)

  for (const file of files) {
    const filePath = path.join(dir, file)
    const stat = fs.statSync(filePath)

    if (stat.isDirectory()) {
      findImages(filePath, images)
    } else {
      const ext = path.extname(file).toLowerCase()
      if (IMAGE_EXTENSIONS.includes(ext)) {
        images.push(filePath)
      }
    }
  }

  return images
}

function generateImageName(imagePath, withExt) {
  const fileName = path.basename(imagePath)
  const withoutExt = withExt
    ? fileName
    : fileName.replace(/\.(png|jpg|jpeg)$/i, '')

  const name = withoutExt
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/__+/g, '_')
    .replace(/^_|_$/g, '')

  return name
}

function generateRelativeImportPath(imagePath) {
  const relativePath = path.relative(path.dirname(OUTPUT_FILE), imagePath)
  return relativePath.startsWith('.') ? relativePath : './' + relativePath
}

function getImageDimensions(imagePath) {
  try {
    const dimensions = imageSize(imagePath)
    return {width: dimensions.width, height: dimensions.height}
  } catch (e) {
    console.warn(`Could not read dimensions for ${imagePath}:`, e.message)
    return {width: 0, height: 0}
  }
}

function generateComponent(images) {
  const imageEntries = images.map((imagePath) => {
    const name = generateImageName(imagePath)
    const importPath = generateRelativeImportPath(imagePath)
    const dimensions = getImageDimensions(imagePath)
    return {name, importPath, dimensions, fullPath: imagePath}
  })

  // Check for duplicates
  const nameMap = new Map()
  for (const entry of imageEntries) {
    if (nameMap.has(entry.name)) {
      const existing = nameMap.get(entry.name)
      console.error(`\nDuplicate image name "${entry.name}" found:`)
      console.error(`  1. ${existing.fullPath}`)
      console.error(`  2. ${entry.fullPath}`)
      console.error('\nPlease rename one of the files to have a unique name.')
      process.exit(1)
    }
    nameMap.set(entry.name, entry)
  }

  imageEntries.sort((a, b) => a.name.localeCompare(b.name))

  const typeUnion = imageEntries.map((e) => `  | '${e.name}'`).join('\n')

  const imagesObject = imageEntries
    .map((e) => `  '${e.name}': require('${e.importPath}'),`)
    .join('\n')

  const sizesObject = imageEntries
    .map(
      (e) =>
        `  '${e.name}': { width: ${e.dimensions.width}, height: ${e.dimensions.height} },`
    )
    .join('\n')

  return `// Auto-generated by scripts/local_image_generator.js
// Do not edit manually

import React from 'react';
import { Image, ImageResizeMode, ImageStyle, StyleProp } from 'react-native';

export type AppLocalImageName =
${typeUnion};

const LocalImages: Record<AppLocalImageName, any> = {
${imagesObject}
};

const LocalImageSizes: Record<AppLocalImageName, { width: number; height: number }> = {
${sizesObject}
};

export interface AppLocalImageProps {
  icon: AppLocalImageName;
  style?: StyleProp<ImageStyle>;
  width?: number;
  height?: number;
  size?: number;
  scale?: number;
  resizeMode?: ImageResizeMode;
}

export const AppLocalImage: React.FC<AppLocalImageProps> = ({
  icon,
  style,
  width,
  height,
  size,
  scale = 1,
  resizeMode = 'stretch',
}) => {
  const imageSource = LocalImages[icon];
  const defaultSize = LocalImageSizes[icon];

  const imageStyle: ImageStyle = {
    width: defaultSize.width / scale,
    height: defaultSize.height / scale,
  };

  if (size) {
    imageStyle.width = size;
    imageStyle.height = size;
  }
  if (width !== undefined) imageStyle.width = width;
  if (height !== undefined) imageStyle.height = height;

  return (
    <Image
      source={imageSource}
      style={[imageStyle, style]}
      resizeMode={resizeMode}
    />
  );
};

`
}

function main() {
  console.log('Scanning for images in', SRC_DIR)

  const images = findImages(SRC_DIR)
  console.log(`Found ${images.length} images`)

  const component = generateComponent(images)

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, {recursive: true})
  }

  fs.writeFileSync(OUTPUT_FILE, component)
  console.log(`Generated ${OUTPUT_FILE}`)

  // Run prettier
  try {
    execSync(`npx prettier --write "${OUTPUT_FILE}"`, {stdio: 'inherit'})
    console.log('Formatted with prettier')
  } catch (e) {
    console.warn('Prettier formatting failed:', e.message)
  }

  console.log('\nImages found:')
  images.forEach((img) => {
    const name = generateImageName(img)
    const dims = getImageDimensions(img)
    console.log(`  ${name} (${dims.width}x${dims.height})`)
  })
}

main()
